//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CASOPRACTICO3.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caso3
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public Nullable<System.DateTime> fecha_emision { get; set; }
        public string descripcion { get; set; }
        public string comentario { get; set; }
        public string url { get; set; }
    }
}
